### ISSUE TITLE
Windows hosts show wrong core count

### ISSUE THREAD

**Issue by handigarde** [DataDog/gohai#8]
Example in org 4456, Windows Server 2008 R2 SP1 host with 4 cores showing as only one:

**Comment by sjenriquez** [comment]
This came up again

* org_id 29153
* AWS AMI for Windows Server 2012 R2

**Comment by JohnLZeller** [comment]
Gohai is actually reporting the number of physical cores on the host; which is does correctly. Specifically when using AWS, they provision instances with some number of vCPUs, which is where the confusion starts. Each vCPU is just half of a physical core, so if there are 16 vCPUs on an instance, then gohai will report 8 cores, because there are only 8 physical cores, and 16 logical processors.
